apiVersion: v1
kind: Service
metadata:
  name: {{ include ".fullname" . }}
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: trading-{{ include ".fullname" . }}@kubernetescrd
spec:
  selector:
    app.kubernetes.io/name: {{ include ".name" . }}
    helm.sh/chart: {{ include ".chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include ".selectorLabels" . | nindent 4 }}
